server:
  port: 12345
spring:
  application:
    name: sduoj-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:tttt0720/configRepo.git
          ignoreLocalSshSettings: true
          privateKey: |
                        -----BEGIN RSA PRIVATE KEY-----
                        MIIEowIBAAKCAQEAnS91wPEogRkyJr244Er2o2zvN7XtZ/gLwigonvWaU0AK/FMV
                        FzweDKju0wfuK0TzbJ4rYKqDS/YaibimLthTSgrOfiBDrWnyxCSYdkl6TzSZUp46
                        jk1c30KzMsIRIsbmHkMjdexrazEzOMCFAg93oiPV/buXhWyjwuvbryWUsDphN3BN
                        4lbt924exGocGl/x8Gxy0o2JqEM/YOvd6Cr46veVfO6ZB6cEFD+XCRbYJ95Va9wF
                        Qut9g4ubB4tMUPR6QpmNrbRkJ9zoewPn99wFYR2OSt3DH/3DBk0EEsKizkFSIJb1
                        Ktvt+1mqRcUaPK1VbyJxeLrG2TogaJcqmAnw3wIDAQABAoIBAHQHSZvwKF8Ls0qH
                        t8XRcDh4vCjaoXGi10MuE7YrRAz59GIIDkSFewULWqfqbbQBBNOD+i80DxFujG5n
                        IDzqMKkySvUtaefDkpGZFfYTDTcUc61Z4Y2Tq9+eQ9tPCAks20cxdiahKzYILnBR
                        JJ29vyiv3VGcPSAfbs7+/b5PNm/SsBqQ6ZyqROupsoJCDH1b57uSgm8AKzPTCuqk
                        vlZ0yhCEIy3CoWGGvJyBFID1Meps/t5COK/53o6x8rqc5Os9iocngNErDRE2IF53
                        t2iZWBrxSV9CbHFUXtEbVvipLM0TV1l4ZjC+mmciSsA/JUeYX/NMX+aaTLxS8J3L
                        na4xOnECgYEAzdHOWQJ2T6iRJgZXVen6D2AtsT0E4OG/W4oG3Wav8s0boiJnbM8c
                        84CiKew7eqpF5DNooFFR+jHup/6K6vnDJwdqMy2SbeqwuNSJN88MG8SXOWOv6xp5
                        tZr5aNDyHKaqcWG7hcihdE4Xyj3LXSCliAy8q67C8kQ4qNb+2Op1gqkCgYEAw4Ip
                        FhUmei0b5oXsuO5WtoiMtDWIWe2X9+WbgozMinZTcL4gHWBphQarlkLmqe6nlfRj
                        NQKFEWptxrlk4k+Yt4sqJYVjWd2g73aZTpUxuM8ngboL8OeeScpgZXHv6DcShJRr
                        IoqIGXlJ2FrwwtYo5kCLW+fwirX/EJ5lAe1BlEcCgYEAuQkhUUZ0ZSMv8xaKV/P1
                        WvNlwM0R4LczmTFbAJr8HfYmHLp/bwQ4i/YeVEBMLPh9wy4wpsjVQXC4lZGzBJMs
                        zp7M7FvRJD51SIXTIzhiM2inZ/HmSyBPQWSlS4Vl1TpFS4/IzfrUpEI9AxZRCVV7
                        W/fPey2vl6ybn7dCAHOw15kCgYArmJy81d6Mo/5yuy58VnlznqNxk/Zhxz96AfNZ
                        ezgpMBWPMHZM1rDw/vnIOgbhodww7hwpN/SgW5E7HSBH7uPpGdk+IK503Z0DiPjK
                        sy4xPdBbdzcucxey8LPqKywKJi207rutKiMLOyaiXjUN3V+laIMq7V+QLuE/vXJc
                        qaFUBQKBgDTjn1jyhE8JS3IZBl3ItH855QzIcYzhruRqsCdLmKjcIjEfxWrcc/Zf
                        pYXDPyp5gdjzziPjzEQje/RjODsobz1ziOIuMCUq19bx9hTN2/JyXuQU0OsX9y/m
                        pAh+CNypLpV/XL1xzyQ7rRC6atF/0gRXpxhpX0gEa0KqRkvoImEx
                        -----END RSA PRIVATE KEY-----