server:
  port: 8090
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5     # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
sduoj:
  jwt:
    secret: sduoj@Login(Auth}*^31)&sducs%   # 登录校验的密钥
    pubKeyPath: C:\\Users\\tttt\\Desktop\\tempProjects\\rsa.pub       # 公钥地址
    priKeyPath: C:\\Users\\tttt\\Desktop\\tempProjects\\rsa.pri       # 私钥地址
    expire: 30                              # 过期时间,单位分钟
    cookieName: SDUOJ_TOKEN                 # cookie的name
    cookieMaxAge: 30                        # cookie的存活时间