server:
  port: 8090
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://192.168.68.132:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5     # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
sduoj:
  jwt:
    secret: sduoj@Login(Auth}*^31)&sducs%   # 登录校验的密钥
#    pubKeyPath: C:\\Users\\tttt\\Desktop\\tempProjects\\rsa.pub
#    priKeyPath: C:\\Users\\tttt\\Desktop\\tempProjects\\rsa.pri
    pubKeyPath: /home/tttt/rsa.pub
    priKeyPath: /home/tttt/rsa.pri
    expire: 30                              # 过期时间,单位分钟
    cookieName: SDUOJ_TOKEN                 # cookie的name
    cookieMaxAge: 86400                     # cookie的存活时间(s)