name: Build and push Docker images

on:
  push:
    branches:
      - stable
  workflow_dispatch: # add manually button

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt-hotspot
          architecture: x64
          cache: gradle

      - name: Gradle Build
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: action.Dockerfile
          platforms: linux/amd64 #,linux/arm64
          push: true
          tags: registry.cn-beijing.aliyuncs.com/sduoj/sduoj-server:latest