name: Build and push Docker images

on:
  push:
    branches:
      - stable
  workflow_dispatch: # add manually button

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt-hotspot
          architecture: x64
          cache: gradle

      - name: Gradle Build
        run: |
          chmod +x ./gradlew
          ./gradlew build --scan

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: microservice.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: lyouyang/sduoj-server:latest
